/**
 * @file inbound.js
 * @author andrew.rapo@jibo.com
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Utilities = require('./utilities/utilities')
const User = require('./user')

module.exports = function inbound (app, body) {

  User.inbound_handler(body, function(messageData) {
    Utilities.sendToCustomChannel(messageData, body, app)
  })

};
